// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVoVgzasSH5qgxVEyv2ZVH2x0ZDD1LScc',
    appId: '1:28857933936:web:e0fefaa73a082757dad4b5',
    messagingSenderId: '28857933936',
    projectId: 'hackthon-5d162',
    authDomain: 'hackthon-5d162.firebaseapp.com',
    storageBucket: 'hackthon-5d162.appspot.com',
    measurementId: 'G-86JGHMHZCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXfkrGFBt55jx9xTaodNIJTlPUIxpJH8w',
    appId: '1:28857933936:android:c0b9b60615fce0e0dad4b5',
    messagingSenderId: '28857933936',
    projectId: 'hackthon-5d162',
    storageBucket: 'hackthon-5d162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvbturAhCRVsIFbEvXveZr2-fNXpBXydc',
    appId: '1:28857933936:ios:9876c691417dec9fdad4b5',
    messagingSenderId: '28857933936',
    projectId: 'hackthon-5d162',
    storageBucket: 'hackthon-5d162.appspot.com',
    iosBundleId: 'com.example.flutterApplicationStreetParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvbturAhCRVsIFbEvXveZr2-fNXpBXydc',
    appId: '1:28857933936:ios:d987ab8de0507214dad4b5',
    messagingSenderId: '28857933936',
    projectId: 'hackthon-5d162',
    storageBucket: 'hackthon-5d162.appspot.com',
    iosBundleId: 'com.example.flutterApplicationStreetParking.RunnerTests',
  );
}
